---
title: "Final Project"
date: "November 26, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width = 10,fig.height = 12,message = FALSE)
```

##Libraries used
```{r results='hide'}
library(corrplot)
library(ggplot2)
library(maps)
library(rbokeh)
library(dplyr)
```

##Load the dataset
```{r house}
house<- read.csv("kc_house_data.csv")
names(house)

```

##Data Exploration
```{r}
summary(house)
str(house)
head(house)
```

##Changing datatypes for categorical variables
```{r}
house$waterfront <- as.factor(house$waterfront)
house$view <- as.factor(house$view)
house$condition <- as.factor(house$condition)
house$grade <- as.factor(house$grade)
house$zipcode <- as.factor(house$zipcode)
```


## Visualization

```{r echo=FALSE}
housecor <- cor(house[c(3:18)])
corrplot(housecor, method = "number")
```

##Modifying the the dataset
```{r}
house_modi=house[c(3:21)]
house_modi$bedbath <- house_modi$bathrooms/house_modi$bedrooms
house_modi$bedbath <- replace(house_modi$bedbath, !is.finite(house_modi$bedbath),0)
house_modi$sqft_living_log <- log10(house_modi$sqft_living)
house_modi$bedbath_log <- log10(house_modi$bedbath)
house_modi$bedbath_log <- replace(house_modi$bedbath_log, !is.finite(house_modi$bedbath_log),0)
house_modi$renov_index <- ifelse(house_modi$yr_renovated != 0, 2016 - house_modi$yr_renovated, 2016 - house_modi$yr_built)
house_modi$total_sqft <- house_modi$sqft_living + house_modi$sqft_lot
house_modi$total_sqft_log <- log10(house_modi$total_sqft)
house_modi$price_per_sqft_living <- (house_modi$price/house_modi$sqft_living)
house_modi$sqft_living15_log <- log10(house_modi$sqft_living15)

```
`

##Generate heatmap
```{r echo=FALSE}
hspricing <- read.csv("kc_house_data.csv", header = TRUE)
hspricing$price_per_sqft_living <- (hspricing$price/hspricing$sqft_living)

price_per_sqft_living_lat_long_map <- gmap(lat = mean(hspricing$lat), lng = mean(hspricing$long), 
                                           zoom = 11,
                                           width = 680, height = 600) %>%
  ly_points(hspricing$long, hspricing$lat, data = hspricing, 
            color = hspricing$price_per_sqft_living, alpha(1)
)
price_per_sqft_living_lat_long_map
```



#Linear model
```{r}
house_sub <- house[,c(3:17,20,21)]
names(house_sub)
house_sub$grade <- recode(house_sub$grade, "c('1','3','4','5','6','7','8','9','10')='0'; else='1'")
house_sub<-house_sub[,-12] 
house_model1 <- lm(house_sub$price ~. , data = house_sub) ##original model excluding id,data, lat and long
summary(house_model1)
step <- stepAIC(house_model1, direction="both")
require("car")    
house_model <- lm(house_modi$price ~. , data = house_modi)
summary(house_model)

```



